version: '3.8'

services:
  backend:
    build: .
    container_name: be-fintrack
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=fintrack_db;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - fintrack-network
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - fintrack-network
    restart: always

networks:
  fintrack-network:
    driver: bridge
